# - Try to find libSzarp
# Once done this will define
#

INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules/SzarpDirs)

IF(NOT SZARP_ROOT_DIR)
     MESSAGE(FATAL_ERROR "SZARP_ROOT_DIR not defined!")
ENDIF(NOT SZARP_ROOT_DIR)

SET(LIBSZARP_FOUND True)
SET(LIBSZARP_LIBRARIES "Szarp")
SET(LIBSZARP_LIBRARY_DIRS "${SZARP_ROOT_DIR}/libSzarp/")
SET(LIBSZARP_INCLUDE_DIRS "${SZARP_ROOT_DIR}/libSzarp/include")

IF(LIBSZARP_FOUND)
   IF(NOT libSzarp_FIND_QUIETLY)
     MESSAGE(STATUS "Found libSzarp: ${LIBSZARP_INCLUDE_DIR}")
   ENDIF(NOT libSzarp_FIND_QUIETLY)
ELSE(LIBSZARP_FOUND)
   IF(libSzarp_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find libSzarp")
   ENDIF(libSzarp_FIND_REQUIRED)
ENDIF(LIBSZARP_FOUND)

