# - Try to find libSzarp
# Once done this will define
#

INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules/SzarpDirs)

IF(NOT SZARP_ROOT_DIR)
     MESSAGE(FATAL_ERROR "SZARP_ROOT_DIR not defined!")
ENDIF(NOT SZARP_ROOT_DIR)

SET(LIBSZARP2_FOUND True)
SET(LIBSZARP2_LIBRARIES "Szarp2")
SET(LIBSZARP2_LIBRARY_DIRS "${SZARP_ROOT_DIR}/libSzarp2/")
SET(LIBSZARP2_INCLUDE_DIRS "${SZARP_ROOT_DIR}/libSzarp2/include")


IF(LIBSZARP2_FOUND)
   IF(NOT libSzarp2_FIND_QUIETLY)
     MESSAGE(STATUS "Found libSzarp2: ${LIBSZARP2_INCLUDE_DIR}")
   ENDIF(NOT libSzarp2_FIND_QUIETLY)
ELSE(LIBSZARP2_FOUND)
   IF(libSzarp2_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find libSzarp2")
   ENDIF(libSzarp2_FIND_REQUIRED)
ENDIF(LIBSZARP2_FOUND)

