# - Try to find wxcommon
# Once done this will define
#

INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules/SzarpDirs)

IF(NOT SZARP_ROOT_DIR)
     MESSAGE(FATAL_ERROR "SZARP_ROOT_DIR not defined!")
ENDIF(NOT SZARP_ROOT_DIR)

SET(WXCOMMON_FOUND True)
SET(WXCOMMON_LIBRARIES "wxcommon")
SET(WXCOMMON_LIBRARY_DIRS "${SZARP_ROOT_DIR}/wx/common/")
SET(WXCOMMON_INCLUDE_DIRS "${SZARP_ROOT_DIR}/wx/common/")


IF(WXCOMMON_FOUND)
   IF(NOT wxcommon_FIND_QUIETLY)
     MESSAGE(STATUS "Found wxcommon: ${WXCOMMON_INCLUDE_DIR}")
   ENDIF(NOT wxcommon_FIND_QUIETLY)
ELSE(WXCOMMON_FOUND)
   IF(wxcommon_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find wxcommon")
   ENDIF(wxcommon_FIND_REQUIRED)
ENDIF(WXCOMMON_FOUND)

