#!/bin/sh
### BEGIN INIT INFO
# Provides:          SZARP
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts SZARP deamons.
# Description:       Starts SZARP parcook server/terminal daemons (depending on SZARP system configuration).
### END INIT INFO
# $Id: parstart_TEMPLATE 6713 2009-05-02 12:39:34Z reksio $
. /lib/lsb/init-functions

# load locales for use at system startup, e.g. for borutadmn
if [ -r /etc/default/locale ]; then
	. /etc/default/locale
	export LANG
fi

# Check for szarp config file.
if [ -f /etc/szarp/parstart.cfg ]; then
       	. /etc/szarp/parstart.cfg
else
	log_failure_msg "Configuration file /etc/szarp/parstart.cfg is missing"
	exit 0
fi

# Check for SZARP dir
[ -d __INSTALL_DIR__/ ] || {
	log_failure_msg "No such directory: __INSTALL_DIR__/"
	exit 1
}

szlog() {
	log_daemon_msg "Starting SZARP" $DAEMON
}

stlog() {
	log_daemon_msg "Stopping SZARP" $DAEMON
}

setulimit() {
	if [ $1 ]; then
	    ulimit -n $1
	fi
}

case "$1" in
    start)
	setulimit $NOFILE_LIMIT
	# enable core dump
	ulimit -c unlimited

	if [ x$PARHUB = x1 ]; then
			DAEMON='parhub'
			szlog
			python /opt/szarp/lib/python/parhub.py start
			worklog $?
	fi

	if [ -x __INSTALL_DIR__/bin/iks-server -a x$IKS_SERVER = x1 ] ; then
	    DAEMON=/opt/szarp/bin/iks-server
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$PROBES_SERVER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/lib/python/probes_server.tac
    	    szlog
	    twistd -y $DAEMON --logfile /opt/szarp/logs/prober.log --pidfile /var/run/probes_server.pid
	    log_end_msg $?
	fi
	
	if [ x$PSERVER_LITE = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/pserver-lite
    	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$MEANER4 = x1 ]; then
	    DAEMON='meaner4'
	    szlog
	    python /opt/szarp/lib/python/meaner4/meaner4dmn.py start
	    log_end_msg $?
	fi

	if [ x$PARCOOK = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/parcook 
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi
	
	if [ x$MEANER3 = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/meaner3
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi
	
	if [ x$PARAMD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/paramd 
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$XSLTD = x1 ]; then
	    log_daemon_msg "Updating xsltd link"
	    ln -sf "__INSTALL_DIR__/$HOST" /etc/szarp/default
	    log_end_msg $?
	fi

	if [ x$SENDER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/sender
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$ANALIZA = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/analiza
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$SSS = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/sss
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$PSETD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/psetd
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$STAMPD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/stampd
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$SSCONF = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/ssconf.py
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$PROBER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/prober
	    szlog
	    start_daemon $DAEMON
	    log_end_msg $?
	fi

	if [ x$REMARKS_SERVER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/remarks_server.py
	    szlog
	    twistd -y $DAEMON --pidfile /var/run/remarks_server.pid -l __INSTALL_DIR__/logs/remarks_server.log
	    log_end_msg $?
	fi
	;;

  stop)
	if [ x$SSS = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/sss
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    worklog $?
	fi

	if [ -x __INSTALL_DIR__/bin/iks-server -a x$IKS_SERVER = x1 ] ; then
	    DAEMON=/opt/szarp/bin/iks-server
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$PROBER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/prober
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$PROBES_SERVER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/lib/python/probes_server.tac
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/probes_server.pid
	    log_end_msg $?
	fi

	if [ x$PSERVER_LITE = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/pserver-lite
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$PSETD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/psetd
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$STAMPD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/stampd
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$SSCONF = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/ssconf.py
	    stlog
	    # we cannot use --exec here because ssconf is run by python interpter
	    PIDFILE=/var/run/ssconf.pid
	    pidof -x $DAEMON > $PIDFILE
	    /sbin/start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
	    log_end_msg $?
	fi

	if [ x$ANALIZA = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/analiza
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$SENDER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/sender
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$MEANER3 = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/meaner3
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
    	    # sometimes meaner3 needs more time
    	    sleep 1
	    log_end_msg $?
	fi

	if [ x$PARAMD = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/paramd 
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$PARCOOK = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/parcook 
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	    log_end_msg $?
	fi

	if [ x$REMARKS_SERVER = x1 ]; then
	    DAEMON=__INSTALL_DIR__/bin/remarks_server.py
	    stlog
	    /sbin/start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/remarks_server.pid
	    log_end_msg $?
	fi

	if [ x$MEANER4 = x1 ]; then
	    DAEMON='meaner4'
	    stlog
	    python /opt/szarp/lib/python/meaner4/meaner4dmn.py stop
	    log_end_msg $?
	fi

	if [ x$PARHUB = x1 ]; then
	    DAEMON='parhub'
	    szlog
	    python /opt/szarp/lib/python/parhub.py stop
	    log_end_msg $?
	fi

	echo -n "(SZARP) Oczekiwanie"
	for i in 1 2 3 ; do {
		echo -n "."
		sleep 1
	}; done
	
	log_daemon_msg "Cleaning IPC resources"
	__INSTALL_DIR__/bin/ipcclean
	log_end_msg $?

	;;
  restart|reload)
	###
	# If ipk2szarp exists check configuration with it and prevent restart if
	# configuration check failed.
	###
	if [ -x __INSTALL_DIR__/bin/ipk2szarp ]; then
		echo "Verifying configuration: __INSTALL_DIR__/ipk2szarp"
		__INSTALL_DIR__/bin/ipk2szarp || { echo "Invalid configuration -- won't restart" 1>&2; exit 1; }
	fi

	;;
  status)
	echo "SZARP programs run: "
	ps axw | grep -v 'grep' | grep "__INSTALL_DIR__/bin" \
		| cut -d ':' -f '2-' | cut -b '4-'
	;;
  *)
	echo "Usage: parstart {start|stop|restart|reload|status}"
	exit 1
	;;
esac

exit 0
