#!/bin/bash
# SZARP: SCADA software 
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# 2005 Praterm S.A.
# Pawe³ Pa³ucha <pawel@praterm.com.pl>
# $Id: get_sysinfo 4393 2007-09-13 16:37:10Z reksio $
#
# Script tries to fetch sysinfo from SZARP terminal hosts.

PATH=/bin:/usr/bin

# Get hostname
HOST=`hostname -s`
if [ -z "$HOST" ] ; then
	echo "Cannot get hostname" 1>&2
	exit 1
fi

# Check if we are SZARP-server
if [ ! -f "/opt/szarp/$HOST/sysinfo_${HOST}_debian" ] ; then
	exit
fi

# Now, search for terminals
for term in `grep $HOST-t /etc/hosts | tr -s '\t' ' ' | cut -f2 -d\  | cut -f1 -d.`; do
	scp -B ${term}:sysinfo_${term}_debian /opt/szarp/${HOST}
done

