#!/bin/bash
# SZARP: SCADA software 
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Kopiuje pliki podane jako argumenty na dyskietkê - albo zamonotowan±, albo
# za pomoc± mcopy.
# 2004 Praterm S.A. <pawel@praterm.com.pl>
#
# $Id: fdcp 4393 2007-09-13 16:37:10Z reksio $

if test $# = 0 ; then
	echo "Copy files to floppy using mtools if floppy is not mounted."
	echo "Usage: fdcp <file> ..."
	exit
fi

if test -d /mnt/floppy ; then
	FDDIR=/mnt/floppy
else
	FDDIR=/floppy
fi

if mount | grep floppy &> /dev/null ; then
	cp -f $* $FDDIR
else
	mcopy -o $* a:
fi
	
