#!/bin/bash
# SZARP: SCADA software 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# i2smo - "ipk2szarp modified only"
# Praterm S.A.
# Pawe³ Pa³ucha <pawel@praterm.com.pl>
# $Id: i2smo 4393 2007-09-13 16:37:10Z reksio $

BINPREFIX="/opt/szarp/bin"

sh -c "$BINPREFIX/ipk2szarp $@"

if [ $? -eq 0 ]
then
	echo "OK"
else
	echo "ERROR"
fi

