#!/bin/sh
# SZARP: SCADA software 
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
# $Id: szarp_scripter 6758 2009-05-22 14:06:19Z pawel $

#
# Script for remotly running users tasks.
#

DEFAULT_SERVER=praterm

user_id=$1
script_id=$2

if [ x$user_id = x ]; then
  echo "no user id given"
  exit 1
fi

if [ x$script_id = x ]; then
  echo "no script id given"
  exit 1
fi

# fetching script
rsync --rsh="ssh -o StrictHostKeyChecking=no" -z $user_id@$DEFAULT_SERVER:scripts/$user_id/$script_id /tmp

# running
sh /tmp/$script_id
