/* 
 SZARP: SCADA software 
 

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */
/*
 * Kontroler 
 * SZARP

 * Adam Smyk asmyk@praterm.pl
 *
 * $Id: kontrtaskbaritem.h 1 2009-06-24 15:09:25Z asmyk $
 */

#ifndef KONTRTASKBARITEM_H_
#define KONTRTASKBARITEM_H_

#ifndef WX_PRECOMP
#include <wx/wx.h>
#include <wx/wxprec.h>
#include <wx/progdlg.h>
#include <wx/cmdline.h>
#include <wx/taskbar.h>
#include <wx/tokenzr.h>
#include <wx/timer.h>
#else
#include <wx/wx.h>
#endif

#include "ballontaskbaritem.h"

#include <vector>

#include "../../resources/wx/icons/kontroler3.xpm"
#include "../../resources/wx/icons/kontroler3_16.xpm"

class szKontroler;

/**class displaying icon on a taskbar
 * and context menu upon mouse click*/
#if defined(__WXMSW__) && defined(__HAS_BALLOON__)
class KontrolerTaskBarItem : public BallonTaskBar {
#else
class KontrolerTaskBarItem : public wxTaskBarIcon {
#endif
DECLARE_EVENT_TABLE()
	/**Creates context menu*/
	virtual wxMenu* CreatePopupMenu();
	/**Handles event generated by "Close application" menu item*/
	void OnCloseMenuEvent(wxCommandEvent &event);
	/**Handles event generated by "About" menu item*/
	void OnAbout(wxCommandEvent &event);
	/**Handles event generated by "Open" menu item*/
	void OnOpen(wxCommandEvent &event);
	/**Handles event generated by pressing left button of mouse*/
	void OnLeftMouseDown(wxTaskBarIconEvent &event);
	/**Icon on the task bar*/
	wxIcon m_kontroler_icon;
	/**Menu*/
	wxMenu * m_menu;
	/**Kontroler main window*/
	szKontroler * m_kontroler;
	/**Kontroler works in remote mode if true*/
	bool m_remote_mode;
	/**Kontroler works in operator mode if true*/
	bool m_operator_mode;
	/**Name of a serwver*/
	wxString m_server;
public:
	KontrolerTaskBarItem(bool, bool, wxString);
};

enum {	
	ID_CLOSE_APP_MENU,
	ID_ABOUT_MENU,
	ID_OPEN_MENU
};

#endif /*KONTRTASKBARITEM_H_*/
