# Searches for an installation of the snap library. On success, it sets the following variables:
#
#   CPPUNIT_FOUND              Set to true to indicate the snap library was found
#   CPPUNIT_INCLUDE_DIRS       The directory containing the header file snap/snap.h
#   CPPUNIT_LIBRARIES          The libraries needed to use the snap library
#
# To specify an additional directory to search, set CPPUNIT_ROOT.

SET(CPPUNIT_INCLUDE_DOC "The directory containing the header file snap7.h")
FIND_PATH(CPPUNIT_INCLUDE_DIRS NAMES cppunit PATHS ${CPPUNIT_ROOT} ${CPPUNIT_ROOT}/include DOC ${CPPUNIT_INCLUDE_DOC} NO_DEFAULT_PATH)
IF(NOT CPPUNIT_INCLUDE_DIRS)  # now look in system locations
  FIND_PATH(CPPUNIT_INCLUDE_DIRS NAMES cppunit DOC ${CPPUNIT_INCLUDE_DOC})
ENDIF(NOT CPPUNIT_INCLUDE_DIRS)

SET(CPPUNIT_FOUND FALSE)

IF(CPPUNIT_INCLUDE_DIRS)
  SET(CPPUNIT_LIBRARY_DIRS ${CPPUNIT_INCLUDE_DIRS})

  IF("${CPPUNIT_LIBRARY_DIRS}" MATCHES "/include$")
    # Strip off the trailing "/include" in the path.
    GET_FILENAME_COMPONENT(CPPUNIT_LIBRARY_DIRS ${CPPUNIT_LIBRARY_DIRS} PATH)
  ENDIF("${CPPUNIT_LIBRARY_DIRS}" MATCHES "/include$")

  IF(EXISTS "${CPPUNIT_LIBRARY_DIRS}/lib")
    SET(CPPUNIT_LIBRARY_DIRS ${CPPUNIT_LIBRARY_DIRS}/lib)
  ENDIF(EXISTS "${CPPUNIT_LIBRARY_DIRS}/lib")

  # Find CPPUNIT libraries
  FIND_LIBRARY(CPPUNIT_RELEASE_LIBRARY NAMES cppunit libcppunit
               PATH_SUFFIXES Release ${CMAKE_LIBRARY_ARCHITECTURE} ${CMAKE_LIBRARY_ARCHITECTURE}/Release
               PATHS ${CPPUNIT_LIBRARY_DIRS} NO_DEFAULT_PATH)

  SET(CPPUNIT_LIBRARIES )
  IF(CPPUNIT_RELEASE_LIBRARY)
    SET(CPPUNIT_LIBRARIES ${CPPUNIT_RELEASE_LIBRARY})
  ENDIF(CPPUNIT_RELEASE_LIBRARY)

  IF(CPPUNIT_LIBRARIES)
    SET(CPPUNIT_FOUND TRUE)
  ENDIF(CPPUNIT_LIBRARIES)
ENDIF(CPPUNIT_INCLUDE_DIRS)

IF(CPPUNIT_FOUND)
  IF(NOT CPPUNIT_FIND_QUIETLY)
    MESSAGE(STATUS "Found CPPUNIT: headers at ${CPPUNIT_INCLUDE_DIRS}, libraries at ${CPPUNIT_LIBRARY_DIRS}")
  ENDIF(NOT CPPUNIT_FIND_QUIETLY)
ELSE(CPPUNIT_FOUND)
  IF(CPPUNIT_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "CPPUNIT library not found")
  ENDIF(CPPUNIT_FIND_REQUIRED)
ENDIF(CPPUNIT_FOUND)
